image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - mysql-build
  - build

mysql_build:
  stage: mysql-build
  variables:
    MYSQL_DATABASE: cicd_security_module
    MYSQL_ROOT_PASSWORD: password
  services:
  - mysql
  image: mysql
  before_script:
  - mysql --version
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

maven-build:
  image: maven:3-jdk-11
  stage: build
  tags:
    - dev2
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
