image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: password

stages:
  - build

maven-build:
  image: maven:3-jdk-11
  services:
  - mysql:5.7
  stage: build
  tags:
    - dev2
  script: 
  - mvn package -B
  artifacts:
    paths:
      - target/*.jar
