variables:
  DOCKER_DRIVER: overlay
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: 123456a@

stages:
  - build
  - build-docker-image
  - push-image-to-gitlab-registry
  - test

maven-build:
  image: maven:3-jdk-11
  stage: build
  tags:
  - dev2
  script: 
  - mvn package -B
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t java-next-generation/hieplaboratory .

push-image-to-gitLab-registry:
  stage: push-image-to-gitlab-registry
  before_script:
    - docker login registry.savvycom.vn -u "$CI_REGISTRY_USER" -p "$CI_GITLAB_TOKEN"
  script:
    - docker info
    - docker tag java-next-generation/hieplaboratory registry.savvycom.vn/java-next-generation/hieplaboratory
    - docker push registry.savvycom.vn/java-next-generation/hieplaboratory

test:
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
