image: docker:latest
services:
  - docker:dind
  - mysql:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: password

stages:
  - build

maven-build:
  image: maven:3-jdk-11
  stage: build
  tags:
    - dev2
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
