variables:
  DOCKER_DRIVER: overlay
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: password
  BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  tags:
  - java
  services:
    - mysql:5.7
  script: 
  - mvn package -B
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  tags:
    - java
  script:
    - docker login registry.savvycom.vn -u "$CI_REGISTRY_USER" -p "$CI_GITLAB_TOKEN"
    - docker pull registry.savvycom.vn/java-next-generation/hieplaboratory
    - docker run --name=$BRANCH -p 8088:8080 -i registry.savvycom.vn/java-next-generation/hieplaboratory
  only:
    - master
