variables:
  DOCKER_DRIVER: overlay
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: password
  BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - java
  dependencies:
    - maven-build
  script:
    - docker login registry.savvycom.vn -u "$CI_REGISTRY_USER" -p "$CI_GITLAB_TOKEN"
    - docker pull registry.savvycom.vn/java-next-generation/hieplaboratory
    - docker run --name=$BRANCH -p 8088:8080 -i registry.savvycom.vn/java-next-generation/hieplaboratory
  only:
    - master
