image: docker:latest
services:
  - docker:dind
  - mysql:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: cicd_security_module
  MYSQL_ROOT_PASSWORD: password

stages:
  - build

maven-build:
  image: maven:3-jdk-11
  services:
  - mysql:latest
  stage: build
  tags:
    - dev2
  script: 
  - apk --no-cache add mysql-client
  - mysql --version
  - sleep 20
  - echo "SHOW tables;"| mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h 127.0.0.1 "${MYSQL_DATABASE}"
  - mvn package -B
  artifacts:
    paths:
      - target/*.jar
